version: 2
builds:
  - id: wdbctl
    main: cmd/wdbctl/main.go
    binary: wdbctl
    goos: [windows, darwin, linux]
    goarch: [amd64, arm, arm64]
    goarm: ["6", "7"]
  - id: wunderdb
    main: cmd/wunderdb/main.go
    binary: wunderdb
    goos: [windows, darwin, linux]
    goarch: [amd64, arm, arm64]
    goarm: ["6", "7"]


archives:
  - id: wdbctl
    name_template: "{{.Binary}}_{{.Version}}_{{.Os}}_{{.Arch}}_{{.Arm}}"
    builds: [wdbctl]
    format: tar.gz
    files:
      - README.md
      - LICENSE
  - id: wunderdb
    name_template: "{{.Binary}}_{{.Version}}_{{.Os}}_{{.Arch}}_{{.Arm}}"
    builds: [wunderdb]
    format: tar.gz
    files:
      - README.md
      - LICENSE

dist: target/dist
brews:
  - name: wdbctl
    ids:
      - "wdbctl"
    homepage: "https://github.com/TanmoySG/wunderDB"
    repository:
      owner: TanmoySG
      name: homebrew-TanmoySG
    commit_author:
      name: TanmoySG
      email: tanmoysps@gmail.com
release:
  github:
    owner: TanmoySG
    name: wunderDB
  disable: false
  target_commitish: '{{ .Commit }}'