name: Railway Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - TagDeploy
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service wunderDB
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
